package com.fitrater.app.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fitrater.app.data.repo.Repo
import com.fitrater.app.ui.theme.Eyebrow
import com.fitrater.app.ui.theme.HemColors
import com.fitrater.app.ui.theme.HemSpace
import com.fitrater.app.ui.theme.HemType
import com.fitrater.app.ui.theme.PrimaryButton
import com.fitrater.app.ui.theme.SerifDisplay
import com.fitrater.app.util.ToastBus
import kotlinx.coroutines.launch

/** Values for `content_reports.content_kind`. Kept here so callers don't hand-type strings. */
object ReportKind {
    const val OUTFIT = "outfit"
    const val STUDIO_PIECE = "studio_piece"
    const val COVER = "cover"
    const val CHAT_MESSAGE = "chat_message"
    const val INVITATION = "invitation"
    const val LETTER = "letter"
}

// Matches the check constraint on content_reports.reason.
private val REASONS = listOf(
    "offensive" to "Offensive or hateful",
    "sexual" to "Sexual content",
    "violent" to "Violent or disturbing",
    "misleading" to "Misleading or wrong about me",
    "other" to "Something else",
)

/**
 * Report sheet for AI-generated output — required by Play's AI-Generated Content
 * policy to sit on the artifact itself, not behind a support email.
 *
 * Drop-in from any screen showing generated content:
 *   if (reporting) ReportContentSheet(ReportKind.OUTFIT, outfitId) { reporting = false }
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportContentSheet(
    contentKind: String,
    contentId: String,
    onDismiss: () -> Unit,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val scope = rememberCoroutineScope()
    var reason by remember(contentId) { mutableStateOf<String?>(null) }
    var note by remember(contentId) { mutableStateOf("") }
    var sending by remember(contentId) { mutableStateOf(false) }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        containerColor = HemColors.Paper,
    ) {
        Column(
            Modifier
                .fillMaxWidth()
                .padding(horizontal = HemSpace.gutter, vertical = HemSpace.md),
        ) {
            Eyebrow("REPORT")
            Spacer(Modifier.height(HemSpace.xs))
            SerifDisplay("What's wrong here?")
            Spacer(Modifier.height(HemSpace.xs))
            Text(
                "This look was generated by AI. Tell us what went wrong and we'll review it.",
                style = HemType.bodyMuted.copy(fontSize = 14.sp),
            )

            Spacer(Modifier.height(HemSpace.lg))
            REASONS.forEach { (value, label) ->
                val selected = reason == value
                Row(
                    Modifier
                        .fillMaxWidth()
                        .padding(bottom = HemSpace.xs)
                        .clip(RoundedCornerShape(999.dp))
                        .background(if (selected) HemColors.Ink else Color.Transparent)
                        .border(1.dp, HemColors.Ink.copy(alpha = 0.4f), RoundedCornerShape(999.dp))
                        .clickable(enabled = !sending) { reason = value }
                        .padding(horizontal = HemSpace.md, vertical = 12.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Start,
                ) {
                    Text(
                        label,
                        style = HemType.body.copy(
                            color = if (selected) Color.White else HemColors.Ink,
                            fontSize = 14.sp,
                        ),
                    )
                }
            }

            Spacer(Modifier.height(HemSpace.md))
            Eyebrow("ANYTHING ELSE (OPTIONAL)")
            Spacer(Modifier.height(HemSpace.xs))
            Box(
                Modifier
                    .fillMaxWidth()
                    .height(80.dp)
                    .clip(RoundedCornerShape(12.dp))
                    .background(HemColors.CardCream)
                    .border(1.dp, HemColors.Hairline, RoundedCornerShape(12.dp))
                    .padding(HemSpace.md),
            ) {
                BasicTextField(
                    value = note,
                    onValueChange = { note = it },
                    enabled = !sending,
                    textStyle = TextStyle(color = HemColors.Ink, fontSize = 14.sp),
                    cursorBrush = SolidColor(HemColors.Ink),
                    modifier = Modifier.fillMaxWidth(),
                )
                if (note.isEmpty()) {
                    Text("Add a detail that helps us review…", style = HemType.bodyMuted.copy(fontSize = 14.sp))
                }
            }

            Spacer(Modifier.height(HemSpace.xl))
            PrimaryButton(
                label = if (sending) "Sending…" else "Send report",
                enabled = reason != null && !sending,
                onClick = {
                    val picked = reason ?: return@PrimaryButton
                    if (sending) return@PrimaryButton
                    sending = true
                    scope.launch {
                        runCatching {
                            Repo.submitContentReport(contentKind, contentId, picked, note)
                        }.onSuccess {
                            ToastBus.post("Thanks — we'll review this.")
                            onDismiss()
                        }.onFailure {
                            ToastBus.post("Couldn't send that: ${it.message ?: "error"}")
                            sending = false
                        }
                    }
                },
            )
            Spacer(Modifier.height(HemSpace.lg))
        }
    }
}
