import SwiftUI
import Supabase

/// Values for `content_reports.content_kind`. Kept here so callers don't
/// hand-type strings. Mirrors Android `ui/components/ReportContentSheet.kt`.
enum ReportKind {
    static let outfit = "outfit"
    static let studioPiece = "studio_piece"
    static let cover = "cover"
    static let chatMessage = "chat_message"
    static let invitation = "invitation"
    static let letter = "letter"
}

/// What the user is reporting. `Identifiable` so a screen can drive the sheet
/// with a single `@State var reportTarget: ReportTarget?` + `.sheet(item:)`.
struct ReportTarget: Identifiable, Equatable {
    let kind: String
    let contentId: String
    var id: String { "\(kind):\(contentId)" }

    init(_ kind: String, _ contentId: String) {
        self.kind = kind
        self.contentId = contentId
    }
}

/// Write-only report submission. Lives here rather than in `Repo` because the
/// table is insert-only by design (see `0006_content_reports.sql` — there is
/// deliberately no select policy), so there is nothing for the repo to cache
/// or read back. Uses the same `Supa.client` access pattern `Repo` uses.
enum ReportService {
    private struct ContentReportInsert: Encodable {
        let user_id: String
        let content_kind: String
        let content_id: String
        let reason: String
        let note: String?
    }

    /// File a report against generated content. Throws on failure so the sheet
    /// can tell the user. Ports Android `Repo.submitContentReport`.
    static func submit(kind: String, contentId: String, reason: String, note: String?) async throws {
        guard let uid = Supa.client.auth.currentUser?.id.uuidString.lowercased() else {
            throw RepoError.notSignedIn
        }
        let trimmed = note?.trimmingCharacters(in: .whitespacesAndNewlines)
        try await Supa.client
            .from("content_reports")
            .insert(ContentReportInsert(
                user_id: uid,
                content_kind: kind,
                content_id: contentId,
                reason: reason,
                note: (trimmed?.isEmpty == false) ? trimmed : nil
            ))
            .execute()
    }
}

/// Report sheet for AI-generated output — the affordance sits on the artifact
/// itself rather than behind a support email, which is what the store review
/// guidance for generative content expects.
///
/// Drop-in from any screen showing generated content:
///   @State private var reportTarget: ReportTarget?
///   …
///   .sheet(item: $reportTarget) { t in
///       ReportContentSheet(target: t) { reportTarget = nil }
///   }
struct ReportContentSheet: View {
    let target: ReportTarget
    let onClose: () -> Void

    /// Matches the check constraint on `content_reports.reason`.
    private static let reasons: [(value: String, label: String)] = [
        ("offensive", "Offensive or hateful"),
        ("sexual", "Sexual content"),
        ("violent", "Violent or disturbing"),
        ("misleading", "Misleading or wrong about me"),
        ("other", "Something else")
    ]

    @State private var reason: String?
    @State private var note: String = ""
    @State private var sending = false

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                HStack(alignment: .top) {
                    VStack(alignment: .leading, spacing: 4) {
                        Eyebrow(text: "REPORT")
                        Text("What's wrong here?")
                            .font(Serif.display(26))
                            .foregroundStyle(Palette.ink)
                    }
                    Spacer()
                    Button(action: onClose) {
                        Text("×").font(Serif.display(28)).foregroundStyle(Palette.ink)
                    }
                }

                Text("This look was generated by AI. Tell us what went wrong and we'll review it.")
                    .font(Serif.body(14))
                    .foregroundStyle(Palette.muted)

                VStack(spacing: 8) {
                    ForEach(Self.reasons, id: \.value) { row in
                        reasonPill(value: row.value, label: row.label)
                    }
                }
                .padding(.top, 4)

                VStack(alignment: .leading, spacing: 8) {
                    Eyebrow(text: "ANYTHING ELSE (OPTIONAL)")
                    ZStack(alignment: .topLeading) {
                        RoundedRectangle(cornerRadius: 12)
                            .fill(Palette.card)
                            .overlay(RoundedRectangle(cornerRadius: 12).stroke(Palette.hairline, lineWidth: 1))
                        if note.isEmpty {
                            Text("Add a detail that helps us review…")
                                .font(Serif.body(14))
                                .foregroundStyle(Palette.muted)
                                .padding(.horizontal, 16)
                                .padding(.vertical, 18)
                                .allowsHitTesting(false)
                        }
                        TextEditor(text: $note)
                            .font(Serif.body(14))
                            .foregroundStyle(Palette.ink)
                            .scrollContentBackground(.hidden)
                            .background(Color.clear)
                            .padding(.horizontal, 11)
                            .padding(.vertical, 10)
                            .disabled(sending)
                    }
                    .frame(height: 96)
                }
                .padding(.top, 4)

                PrimaryButton(
                    title: sending ? "Sending…" : "Send report",
                    enabled: reason != nil && !sending
                ) { submit() }
                .padding(.top, 8)

                Spacer().frame(height: 12)
            }
            .padding(20)
        }
        .background(Palette.paper.ignoresSafeArea())
    }

    private func reasonPill(value: String, label: String) -> some View {
        let selected = reason == value
        return Button(action: {
            guard !sending else { return }
            Haptic.tap()
            reason = value
        }) {
            HStack {
                Text(label)
                    .font(Serif.body(14))
                    .foregroundStyle(selected ? .white : Palette.ink)
                Spacer()
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(selected ? Palette.ink : Color.clear)
            .overlay(Capsule().stroke(Palette.ink.opacity(0.4), lineWidth: 1))
            .clipShape(Capsule())
            .contentShape(Capsule())
        }
        .buttonStyle(.plain)
        .disabled(sending)
    }

    @MainActor
    private func submit() {
        guard let picked = reason, !sending else { return }
        sending = true
        Task {
            do {
                try await ReportService.submit(
                    kind: target.kind,
                    contentId: target.contentId,
                    reason: picked,
                    note: note
                )
                ToastBus.shared.post("Thanks — we'll review this.")
                onClose()
            } catch {
                ToastBus.shared.post("Couldn't send that: \(error.localizedDescription)")
                sending = false
            }
        }
    }
}
