import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell, LegalSection } from "@/components/legal";

export const metadata: Metadata = {
  title: "Support — Fitrater",
  description: "Get help with Fitrater: contact, FAQ, billing, and account deletion.",
};

const CONTACT = "efe@cloudgeng.com";

export default function SupportPage() {
  return (
    <LegalShell title="Support" updated="1 September 2026">
      <LegalSection heading="Get help">
        <p>
          Email{" "}
          <a className="underline" href={`mailto:${CONTACT}`}>{CONTACT}</a>{" "}
          and we will reply within two business days. Write from the address
          linked to your account, and tell us the platform (iPhone or Android)
          and what you were doing when it went wrong — it saves a round trip.
        </p>
        <p>
          You can reach the same address from inside the app: the{" "}
          <strong>You</strong> tab &rarr; <strong>Help &amp; privacy</strong>{" "}
          &rarr; <strong>Contact support</strong>.
        </p>
      </LegalSection>

      <LegalSection heading="What Fitrater does">
        <p>
          Fitrater is an AI styling app. You photograph a look and Hem, the
          app&rsquo;s stylist, answers: <strong>Score a look</strong> (one
          honest number plus per-piece notes), <strong>A vs B</strong> (two
          photos, one winner), <strong>Try on</strong> (wear a garment on your
          own photo), <strong>Decode style</strong> (break a reference image
          down into its pieces), <strong>Occasion Coach</strong> (three outfits
          for a specific moment), <strong>Compose a cover</strong> (turn a fit
          into an editorial cover), and <strong>Chat with Hem</strong>. Your
          closet and Studio pieces are saved to your account, and a short
          Sunday letter recaps the week.
        </p>
        <p>
          Every result is generated by an AI model. It is style guidance and
          entertainment — an opinion, not a fact about you, and not
          professional advice.
        </p>
      </LegalSection>

      <LegalSection heading="Frequently asked">
        <p>
          <strong>How do credits work?</strong> Each AI action costs credits,
          and the cost is shown next to the action before you spend anything.
          Credits are granted when you sign up, included with a Fitrater Pro
          subscription, or bought as one-time packs. Chat with Hem is free.
          Credits have no monetary value and are not transferable.
        </p>
        <p>
          <strong>What does Fitrater Pro cost?</strong> $14.99 per month with a
          3-day free trial, or $79.99 per year with a 7-day free trial. Prices
          are in USD; your store shows the price in your local currency. Pro
          unlocks Try-on, the Sunday letter, Studio without the free cap, and
          Hem&rsquo;s full memory.
        </p>
        <p>
          <strong>How do I cancel?</strong> Subscriptions are billed by Apple
          or Google, not by us, and renew until you cancel. Cancel in{" "}
          <em>Settings &rarr; your name &rarr; Subscriptions</em> on iPhone, or
          in the Google Play app under <em>Payments &amp; subscriptions</em>.
          Deleting the app does not cancel a subscription.
        </p>
        <p>
          <strong>I paid but Pro is not showing.</strong> Open the{" "}
          <strong>You</strong> tab &rarr; <strong>Buy credits</strong> and tap{" "}
          <strong>Restore purchases</strong>, making sure you are signed in to
          the same store account you bought with. If it still does not appear,
          email us with your purchase receipt.
        </p>
        <p>
          <strong>Can I get a refund?</strong> Refunds are handled by the store
          you bought from, under its policy — Apple at{" "}
          <a
            className="underline"
            href="https://reportaproblem.apple.com"
            target="_blank"
            rel="noreferrer"
          >
            reportaproblem.apple.com
          </a>
          , Google at{" "}
          <a
            className="underline"
            href="https://play.google.com/store/account/subscriptions"
            target="_blank"
            rel="noreferrer"
          >
            Google Play subscriptions
          </a>
          . Write to us as well and we will help where we can.
        </p>
        <p>
          <strong>What happens to my photos?</strong> Photos you capture or
          upload are stored with your account and shared with our AI processing
          providers only to produce the result you asked for. They are not sold
          and not used for advertising. Deleting your account deletes them.
        </p>
        <p>
          <strong>How do I get my data out?</strong> The <strong>You</strong>{" "}
          tab &rarr; <strong>Help &amp; privacy</strong> &rarr;{" "}
          <strong>Export my data</strong> gives you everything we hold as JSON.
        </p>
        <p>
          <strong>Something looks wrong or offensive.</strong> Tell us at{" "}
          <a className="underline" href={`mailto:${CONTACT}`}>{CONTACT}</a> and
          include a screenshot. We review reports and can remove content and
          suspend accounts that break the{" "}
          <Link className="underline" href="/terms">
            Terms of Service
          </Link>
          .
        </p>
        <p>
          <strong>How old do I have to be?</strong> Fitrater is for people aged
          16 and over.
        </p>
      </LegalSection>

      <LegalSection heading="Account and legal">
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <Link className="underline" href="/delete-account">
              Delete your account
            </Link>{" "}
            — how to remove your account and everything in it.
          </li>
          <li>
            <Link className="underline" href="/privacy">
              Privacy Policy
            </Link>{" "}
            — what we collect and who processes it.
          </li>
          <li>
            <Link className="underline" href="/terms">
              Terms of Service
            </Link>{" "}
            — the rules for using Fitrater.
          </li>
        </ul>
        <p>
          Fitrater is operated by Cloudgeng, based in the Netherlands. For
          anything not covered above, email{" "}
          <a className="underline" href={`mailto:${CONTACT}`}>{CONTACT}</a>.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
