package com.fitrater.app.nav

object Route {
    const val Splash = "splash"
    const val SignIn = "signin"
    const val Onboard1 = "onboard1"
    const val Onboard2 = "onboard2"
    const val Paywall = "paywall"
    const val Shell = "shell"
    const val Home = "home"
    const val ScoreDetail = "score_detail/{outfitId}"
    fun scoreDetail(outfitId: String) = "score_detail/$outfitId"
    const val Studio = "studio"
    const val Journal = "journal"
    const val You = "you"
    const val ScoreSheet = "score_sheet"
    const val StudioCreate = "studio/create"
    const val WeeklyLetter = "weekly_letter"
    const val StyleProfile = "style_profile"
    const val Appearance = "appearance"
    const val ManagePro = "manage_pro"
    const val HelpPrivacy = "help_privacy"
    const val FaqScreen = "faq"
    const val Licenses = "licenses"
    const val Camera = "camera"
    const val TryOn = "tryon"
    const val Versus = "versus"
    const val Roast = "roast"
    const val Decode = "decode"
}
